rm zero_state.json
rm ton-global.config.json
rm ton-global.config.json.tmp
rm config1.json
rm config2.json
rm config3.json
rm config4.json
rm config5.json
rm genkey1
rm genkey2
rm genkey3
rm genkey4
rm genkey5
rm console1.json
rm console2.json
rm console3.json
rm console4.json
rm console5.json
rm /shared/output_*.log
rm $TEST_ROOT/zero_state_tmp.json
rm $TEST_ROOT/zero_state_tmp_2.json

